
version: 2.1
executors:
    my-executor:
        docker:
          - image: circleci/node:8
jobs:
    build:
      working_directory: ~/repo
      executor: my-executor
      steps:
          - checkout
          - restore_cache:
              key: npm-{{ checksum "package.json" }}
          - run: |
              npm install
          - save_cache:
              paths:
                - node_modules
              key: npm-{{ checksum "package.json" }}
    deploy-prod:
      executor: my-executor
      working_directory: ~/repo
      steps:
          - checkout
          - run: npm install
          - run: |
              npm run generate
              ./node_modules/.bin/gulp deploy
workflows:
    version: 2
    build-deploy:
      jobs:
          - build:
              filters:
                branches:
                  ignore: master
          - deploy-prod:
              filters:
                branches:
                  only: master